name: Nightly

on:
  schedule:
    - cron: "17 3 * * *"
      timezone: "Europe/Berlin"
  workflow_dispatch:
    inputs:
      java-version:
        description: 'The Java version to use'
        required: true
        default: 25
        type: choice
        options:
          - 21
          - 25
      smoke-test:
        description: 'Whether to run a smoke test or not'
        required: true
        default: true
        type: boolean
      image-tag:
        description: 'Tag for the image'
        required: true
        default: '1.0.0'
        type: string

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Run mvn action
        id: runMvnAction
        uses: ./.github/actions/maven
        with:
          java-version: ${{ github.event_name == 'schedule' && '25' || inputs.java-version }}
          goal: 'test'
      
  smoke-test:
    if: (github.event_name == 'schedule') || (inputs.smoke-test || false) == true
    uses: ./.github/workflows/smoke-test.yml
    with:
      image-tag: ${{ inputs.image-tag || '1.0.0' }}
  
  report:
    needs: smoke-test
    runs-on: ubuntu-latest
    env:
      RESPONSE: ${{ needs.smoke-test.outputs.response }}
    steps:
      - name: Schreibe in Summary
        run: |
          echo "Antwort der Anwednung: $RESPONSE" >> "$GITHUB_STEP_SUMMARY"
