name: Nightly

on:
  schedule:
    - cron: "17 3 * * *"
      timezone: "Europe/Berlin"
  workflow_dispatch:
    inputs:
      java-version:
        description: 'The Java version to use'
        required: true
        default: 25
        type: choice
        options:
          - 21
          - 25
      smoke-test:
        description: 'Whether to run a smoke test or not'
        required: true
        default: true
        type: boolean
      image-tag:
        description: 'Tag for the image'
        required: true
        default: '1.0.0'
        type: string

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Setup java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: ${{ github.event_name == 'schedule' && '25' || inputs.java-version }}
          cache: maven
      - run: mvn -B test
  smoke-test:
    runs-on: ubuntu-latest
    if: (github.event_name == 'schedule') || (inputs.smoke-test || false) == true
    env:
      IMAGE: ghcr.io/${{ github.repository }}:${{ inputs.image-tag || '1.0.0' }}
    steps:
      - name: Startup container
        run: | 
          "docker run --name greeter -d -p 8080:8080 $IMAGE"
      - name: Do test
        run: curl -fsS --retry 10 --retry-all-errors --retry-delay 1 "http://localhost:8080/?name=CI"