name: PR-Titel

on:
    pull_request:
        branches:
            - main
        types: [opened, edited, synchronize, reopened]

permissions: {}

jobs:
    title:
        runs-on: ubuntu-latest
        env:
            TITLE: ${{ github.event.pull_request.title }}
        steps:
            - name: Write title into summary
              run: | 
                echo "PR-Titel: $TITLE" >> "$GITHUB_STEP_SUMMARY"
