name: Smoke test

on: 
  workflow_call:
    inputs:
      image-tag:
        description: "Tag für das Image"
        required: true
        type: string
    outputs:
      response:
        description: "Die Antwort der Anwendung auf den Aufruf."
        value: ${{ jobs.smoke-test.outputs.response }}

permissions: {}

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/${{ github.repository }}:${{ inputs.image-tag }}
    outputs:
      response: ${{ steps.checkAnswer.outputs.response }}
    steps:
      - name: Container starten
        run: docker run --name greeter -d -p 8080:8080 "$IMAGE"
      - name: Antwort prüfen
        id: checkAnswer
        uses: bauben/http-check-action@v1
        with:
          url: "http://localhost:8080/?name=CI"
          expected: "Hallo, CI!"
          retries: "15"
      - name: Wenn Fehler, dann docker logs
        if: ${{ failure() }}
        run: |
          docker logs greeter